# -*- coding: utf-8 -*-
"""student-03-5ea84a8dbe82 (Mar 26, 2026, 7:23:55 AM)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-02-43b1f06a9ba5/locations/us-central1/repositories/e3687950-a573-4c54-993e-4dbd9b902556
"""

from google.cloud import bigquery

client = bigquery.Client(project="qwiklabs-gcp-02-43b1f06a9ba5")

PROJECT_ID = "qwiklabs-gcp-02-43b1f06a9ba5"
DATASET_ID = "fraud_detection"
SOURCE_FILE = "gs://labs.roitraining.com/data-to-ai-workshop/fraud_data_raw.csv"
RAW_TABLE = "fraud_data_raw"

dataset_ref = bigquery.Dataset(f"{PROJECT_ID}.{DATASET_ID}")
dataset_ref.location = "US"
client.create_dataset(dataset_ref, exists_ok=True)

table_id = f"{PROJECT_ID}.{DATASET_ID}.{RAW_TABLE}"

job_config = bigquery.LoadJobConfig(
    source_format=bigquery.SourceFormat.CSV,
    skip_leading_rows=1,
    autodetect=True,
    write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE,
)

load_job = client.load_table_from_uri(SOURCE_FILE, table_id, job_config=job_config)
load_job.result()

print("Loaded to:", table_id)
print("Row count:", client.get_table(table_id).num_rows)

def distinct_vals(col):
    sql = f"SELECT {col} AS val, COUNT(*) cnt FROM `{raw_table_id}` GROUP BY val ORDER BY cnt DESC"
    return client.query(sql).to_dataframe()

distinct_vals("Employment_Status").head(50), distinct_vals("Device_Type").head(50)

client.query(f"SELECT * FROM `{raw_table_id}` LIMIT 5").to_dataframe()

client = bigquery.Client(project="qwiklabs-gcp-02-43b1f06a9ba5")

sql = """
CREATE OR REPLACE TABLE `qwiklabs-gcp-02-43b1f06a9ba5.fraud_detection.fraud_training_data` AS
SELECT
  -- keep raw numeric/boolean fields, drop high-cardinality + fields we’ll encode/bin
  r.* EXCEPT(Applicant_ID, IP_Address, Employment_Status, Device_Type, Age, Previous_Assistance_Date, Application_Date),

  -- Label (rename for clarity)
  CAST(r.Fraudulent AS INT64) AS is_fraud,

  -- One-hot: Employment_Status
  CASE WHEN r.Employment_Status = 'Employed' THEN 1 ELSE 0 END AS emp_employed,
  CASE WHEN r.Employment_Status = 'Unemployed' THEN 1 ELSE 0 END AS emp_unemployed,
  CASE WHEN r.Employment_Status = 'Student' THEN 1 ELSE 0 END AS emp_student,
  CASE WHEN r.Employment_Status = 'Self-Employed' THEN 1 ELSE 0 END AS emp_self_employed,
  CASE WHEN r.Employment_Status = 'Retired' THEN 1 ELSE 0 END AS emp_retired,
  CASE WHEN r.Employment_Status IS NULL
        OR r.Employment_Status IN ('Employed','Unemployed','Student','Self-Employed','Retired')
       THEN 0 ELSE 1 END AS emp_other,

  -- One-hot: Device_Type
  CASE WHEN r.Device_Type = 'Mobile' THEN 1 ELSE 0 END AS dev_mobile,
  CASE WHEN r.Device_Type = 'Desktop' THEN 1 ELSE 0 END AS dev_desktop,
  CASE WHEN r.Device_Type = 'Tablet' THEN 1 ELSE 0 END AS dev_tablet,
  CASE WHEN r.Device_Type IS NULL
        OR r.Device_Type IN ('Mobile','Desktop','Tablet')
       THEN 0 ELSE 1 END AS dev_other,

  -- Age bins
  CASE WHEN r.Age BETWEEN 18 AND 24 THEN 1 ELSE 0 END AS age_18_24,
  CASE WHEN r.Age BETWEEN 25 AND 34 THEN 1 ELSE 0 END AS age_25_34,
  CASE WHEN r.Age BETWEEN 35 AND 44 THEN 1 ELSE 0 END AS age_35_44,
  CASE WHEN r.Age BETWEEN 45 AND 54 THEN 1 ELSE 0 END AS age_45_54,
  CASE WHEN r.Age BETWEEN 55 AND 64 THEN 1 ELSE 0 END AS age_55_64,
  CASE WHEN r.Age >= 65 THEN 1 ELSE 0 END AS age_65_plus,

  -- Ratio
  SAFE_DIVIDE(r.Income, NULLIF(r.Amount_Requested, 0)) AS income_to_amount_requested,

  -- Time since previous assistance (days) using DATE columns
  CASE
    WHEN r.Previous_Assistance_Received IS TRUE AND r.Previous_Assistance_Date IS NOT NULL AND r.Application_Date IS NOT NULL
      THEN DATE_DIFF(r.Application_Date, r.Previous_Assistance_Date, DAY)
    ELSE NULL
  END AS days_since_previous_assistance,

  EXTRACT(YEAR FROM r.Application_Date) AS application_year,
  EXTRACT(MONTH FROM r.Application_Date) AS application_month,
  EXTRACT(DAYOFWEEK FROM r.Application_Date) AS application_dow

FROM `qwiklabs-gcp-02-43b1f06a9ba5.fraud_detection.fraud_data_raw` r;
"""
client.query(sql).result()
print("Created fraud_training_data")

client = bigquery.Client(project="qwiklabs-gcp-02-43b1f06a9ba5")

tbl = client.get_table("qwiklabs-gcp-02-43b1f06a9ba5.fraud_detection.fraud_training_data")
print("Rows:", tbl.num_rows)
print("Columns:", len(tbl.schema))

client.query("""
SELECT *
FROM `qwiklabs-gcp-02-43b1f06a9ba5.fraud_detection.fraud_training_data`
LIMIT 10
""").to_dataframe()

[(f.name, f.field_type) for f in client.get_table(
  "qwiklabs-gcp-02-43b1f06a9ba5.fraud_detection.fraud_training_data"
).schema]

sql = """
SELECT
  COUNT(*) AS row_count,
  SUM(is_fraud) AS fraud_row_count,
  AVG(income_to_amount_requested) AS avg_income_to_amount,
  COUNTIF(days_since_previous_assistance IS NULL) AS null_days_since_prev,
  SUM(emp_employed) AS emp_employed_ones,
  SUM(dev_mobile) AS dev_mobile_ones
FROM `qwiklabs-gcp-02-43b1f06a9ba5.fraud_detection.fraud_training_data`
"""
df = client.query(sql).to_dataframe()
df