# -*- coding: utf-8 -*-
"""student-03-5ea84a8dbe82 (Mar 26, 2026, 8:52:42 AM)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-02-43b1f06a9ba5/locations/us-central1/repositories/650455ed-0be2-49d2-a7e8-98bddfd3bd4b
"""

from google.cloud import bigquery

client = bigquery.Client()
project_id = client.project
dataset_id = "workshop"
table_id = f"{project_id}.{dataset_id}.emergency_calls_external"
gcs_uri = "gs://labs.roitraining.com/data-to-ai-workshop/emergency_calls_response_times.csv"

# Create dataset (schema) if needed
client.create_dataset(bigquery.Dataset(f"{project_id}.{dataset_id}"), exists_ok=True)

# Create external table with autodetect
table = bigquery.Table(table_id)
external_config = bigquery.ExternalConfig("CSV")
external_config.source_uris = [gcs_uri]
external_config.options.skip_leading_rows = 1
external_config.autodetect = True
table.external_data_configuration = external_config

table = client.create_table(table, exists_ok=True)
print("Created:", table.full_table_id)

sql = f"""
SELECT *
FROM `{table_id}`
LIMIT 200
"""
df = client.query(sql).to_dataframe()
df

client = bigquery.Client()

project_id = client.project
dataset_id = "workshop"
external_table_id = f"{project_id}.{dataset_id}.emergency_calls_external"
native_table_id   = f"{project_id}.{dataset_id}.emergency_calls_native"
model_id          = f"{project_id}.{dataset_id}.response_time_model"

def qdf(sql: str):
    return client.query(sql).to_dataframe(create_bqstorage_client=False)
qdf(f"SELECT * FROM `{external_table_id}` LIMIT 20")

client.query(f"""
CREATE OR REPLACE TABLE `{native_table_id}` AS
SELECT
  SAFE_CAST(response_time AS FLOAT64) AS response_time,
  * EXCEPT(response_time)
FROM `{external_table_id}`
WHERE SAFE_CAST(response_time AS FLOAT64) IS NOT NULL
""").result()

qdf(f"SELECT * FROM `{native_table_id}` LIMIT 20")

# Rebuild the native training table with engineered timestamp features
client.query(f"""
CREATE OR REPLACE TABLE `{native_table_id}` AS
SELECT
  SAFE_CAST(response_time AS FLOAT64) AS response_time,


  EXTRACT(DAYOFWEEK FROM call_timestamp) AS call_dow,
  EXTRACT(HOUR FROM call_timestamp) AS call_hour,


  * EXCEPT(response_time, call_timestamp)
FROM `{external_table_id}`
WHERE SAFE_CAST(response_time AS FLOAT64) IS NOT NULL
""").result()

qdf(f"SELECT * FROM `{native_table_id}` LIMIT 20")

running = list(client.list_jobs(state_filter="running", all_users=False))
[(j.job_id, getattr(j, "location", None), j.job_type) for j in running][:20]

suspects = []
for j in running:
    job = client.get_job(j.job_id, location=getattr(j, "location", None))
    sql = getattr(getattr(job, "configuration", None), "query", None)
    sql_text = getattr(sql, "query", "") if sql else ""
    if "CREATE OR REPLACE MODEL" in sql_text and str(model_id) in sql_text:
        suspects.append((job.job_id, getattr(job, "location", None)))

for job_id, loc in suspects:
    client.cancel_job(job_id, location=loc)
suspects

train_sql = f"""
CREATE OR REPLACE MODEL `{model_id}`
OPTIONS(
  model_type='BOOSTED_TREE_REGRESSOR',
  input_label_cols=['response_time'],
  data_split_method='RANDOM',
  data_split_eval_fraction=0.2
) AS
SELECT
  SAFE_CAST(time_of_day AS INT64)            AS time_of_day,
  traffic_level                               AS traffic_level,
  SAFE_CAST(distance_to_station AS FLOAT64)   AS distance_to_station,
  SAFE_CAST(units_available AS INT64)         AS units_available,
  SAFE_CAST(response_time AS FLOAT64)         AS response_time
FROM `{native_table_id}`
WHERE SAFE_CAST(response_time AS FLOAT64) IS NOT NULL
"""

client.query(train_sql).result()

# Evaluate
eval_sql = f"SELECT * FROM ML.EVALUATE(MODEL `{model_id}`)"
eval_df = qdf(eval_sql)
eval_df

predict_sql = f"""
SELECT
  *
FROM ML.PREDICT(
  MODEL `{model_id}`,
  (
    SELECT 14 AS time_of_day, 'High'   AS traffic_level, 14.79 AS distance_to_station, 7 AS units_available
    UNION ALL
    SELECT  9 AS time_of_day, 'Medium' AS traffic_level, 22.76 AS distance_to_station, 6 AS units_available
    UNION ALL
    SELECT 23 AS time_of_day, 'Low'    AS traffic_level,  5.10 AS distance_to_station, 2 AS units_available
  )
)
"""
pred_df = client.query(predict_sql).to_dataframe()
pred_df