# -*- coding: utf-8 -*-
"""student-03-5ea84a8dbe82 (Mar 26, 2026, 3:34:00 PM)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-02-43b1f06a9ba5/locations/us-central1/repositories/e2c4ab37-14e0-4ea0-9e38-6cb40219e9b8
"""

from google.cloud import bigquery

client = bigquery.Client()

project_id = client.project
dataset_id = "workshop"
table_id = f"{project_id}.{dataset_id}.weather_external"
gcs_uri = "gs://labs.roitraining.com/data-to-ai-workshop/weather_data.csv"


# Create external table with autodetect
table = bigquery.Table(table_id)
external_config = bigquery.ExternalConfig("CSV")
external_config.source_uris = [gcs_uri]
external_config.options.skip_leading_rows = 1
external_config.autodetect = True
table.external_data_configuration = external_config

table = client.create_table(table, exists_ok=True)
print("Created:", table.full_table_id)


sql = f"""
SELECT COUNT(*) AS row_count
FROM `{table_id}`
"""
count_df = client.query(sql).to_dataframe()

sql_preview = f"""
SELECT *
FROM `{table_id}`
LIMIT 10
"""
preview_df = client.query(sql_preview).to_dataframe()

count_df, preview_df

client = bigquery.Client()

project_id = client.project
dataset_id = "workshop"
table_id = f"{project_id}.{dataset_id}.weather_external"

sql_cols = f"""
SELECT column_name, data_type
FROM `{project_id}.{dataset_id}.INFORMATION_SCHEMA.COLUMNS`
WHERE table_name = 'weather_external'
ORDER BY ordinal_position
"""
cols_df = client.query(sql_cols).to_dataframe()

# Preview a few rows
preview_df = client.query(f"SELECT * FROM `{table_id}` LIMIT 5").to_dataframe()

cols_df, preview_df

project_id = client.project
dataset_id = "workshop"
dataset_ref = bigquery.DatasetReference(project_id, dataset_id)

model_name = "gemini_remote_model"
model_id = f"{project_id}.{dataset_id}.{model_name}"

# Try a few commonly-available endpoints (stop at first success)
endpoints_to_try = [
    "gemini-2.0-flash",
    "gemini-2.5-flash",
    "gemini-1.5-flash-001",
    "gemini-1.0-pro",
]

last_error = None
created_with = None

for ep in endpoints_to_try:
    sql_create_model = f"""
    CREATE OR REPLACE MODEL `{model_id}`
    REMOTE WITH CONNECTION DEFAULT
    OPTIONS (ENDPOINT = '{ep}');
    """
    try:
        client.query(sql_create_model).result()
        created_with = ep
        print("Created model with ENDPOINT =", ep)
        break
    except Exception as e:
        print("Failed ENDPOINT =", ep)
        last_error = e

if created_with is None:
    raise RuntimeError(f"All endpoints failed. Last error: {last_error}")

models = list(client.list_models(dataset_ref))
[(m.model_id, m.model_type) for m in models if m.model_id == model_name]

dataset_id = "workshop"

# Confirm the model name in your dataset (API-based; avoids INFORMATION_SCHEMA permissions)
models = list(client.list_models(f"{project_id}.{dataset_id}"))
[(m.model_id, m.model_type) for m in models]

weather_table = f"{project_id}.{dataset_id}.weather_external"
model_id = f"{project_id}.{dataset_id}.gemini_remote_model"

sql_preview = f"""
WITH sample AS (
  SELECT
    date, city, state, temperature_f, wind_speed_mph, precipitation_in,
    barometric_pressure_inHg, humidity_percent, weather_condition,
    CONCAT(
      'You are a meteorologist. Write a concise weather report (1–3 sentences). ',
      'Include: Risk level (None/Low/Medium/High) and one recommended action. ',
      'Use only these facts: ',
      TO_JSON_STRING(STRUCT(
        date, city, state, temperature_f, wind_speed_mph, precipitation_in,
        barometric_pressure_inHg, humidity_percent, weather_condition
      ))
    ) AS prompt
  FROM `{weather_table}`
  LIMIT 10
)
SELECT
  date, city, state, temperature_f, wind_speed_mph, precipitation_in,
  barometric_pressure_inHg, humidity_percent, weather_condition,
  ml_generate_text_llm_result AS weather_report,
  ml_generate_text_status
FROM ML.GENERATE_TEXT(
  MODEL `{model_id}`,
  TABLE sample,
  STRUCT(
    0.2 AS temperature,
    256 AS max_output_tokens,
    TRUE AS flatten_json_output
  )
)
"""
preview_reports_df = client.query(sql_preview).to_dataframe()
preview_reports_df