# -*- coding: utf-8 -*-
"""student-03-5ea84a8dbe82 (Mar 27, 2026, 1:00:32 PM)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-02-43b1f06a9ba5/locations/us-central1/repositories/58e3681d-890d-4937-972d-c36adb092645
"""

from google.cloud import bigquery

client = bigquery.Client()
project_id = client.project

dataset_id = "pubsub_feed"
location = "US"

dataset_ref = bigquery.Dataset(f"{project_id}.{dataset_id}")
dataset_ref.location = location

client.create_dataset(dataset_ref, exists_ok=True)
print(f"Dataset ready: {project_id}.{dataset_id} (location={location})")

schema = [
    bigquery.SchemaField(
        "MT", "STRING", mode="NULLABLE",
        description="SEL ID AIR STA CLK MSG info http://woodair.net/sbs/Article/Barebones42_Socket_Data.htm"
    ),
    bigquery.SchemaField("TT", "INT64", mode="NULLABLE", description="1 - 8"),
    bigquery.SchemaField("SID", "STRING", mode="NULLABLE", description="Database Session record number"),
    bigquery.SchemaField("AID", "STRING", mode="NULLABLE", description="Database Aircraft record number"),
    bigquery.SchemaField(
        "Hex", "STRING", mode="NULLABLE",
        description="Aircraft Mode S hexadecimal code https://opensky-network.org/datasets/metadata/"
    ),
    bigquery.SchemaField("FID", "STRING", mode="NULLABLE", description="Database Flight record number"),
    bigquery.SchemaField("DMG", "DATE", mode="NULLABLE", description="Date message generated"),
    bigquery.SchemaField("TMG", "TIME", mode="NULLABLE", description="Time message generated"),
    bigquery.SchemaField("DML", "DATE", mode="NULLABLE", description="Date message logged"),
    bigquery.SchemaField("TML", "TIME", mode="NULLABLE", description="Time message logged"),
    bigquery.SchemaField("CS", "STRING", mode="NULLABLE", description="Callsign (flight number or registration)"),
    bigquery.SchemaField("Alt", "INT64", mode="NULLABLE", description="Mode C altitude (Flight Level)"),
    bigquery.SchemaField("GS", "INT64", mode="NULLABLE", description="Ground Speed"),
    bigquery.SchemaField("Trk", "INT64", mode="NULLABLE", description="Track"),
    bigquery.SchemaField("Lat", "FLOAT64", mode="NULLABLE", description="Latitude (N/E positive, S/W negative)"),
    bigquery.SchemaField("Lng", "FLOAT64", mode="NULLABLE", description="Longitude (N/E positive, S/W negative)"),
    bigquery.SchemaField("VR", "INT64", mode="NULLABLE", description="Vertical Rate"),
    bigquery.SchemaField("Sq", "STRING", mode="NULLABLE", description="Assigned Mode A squawk code"),
    bigquery.SchemaField("Alrt", "INT64", mode="NULLABLE", description="Flag to indicate squawk has changed"),
    bigquery.SchemaField("Emer", "INT64", mode="NULLABLE", description="Flag to indicate emergency code has been set"),
    bigquery.SchemaField("SPI", "INT64", mode="NULLABLE", description="Flag to indicate transponder Ident activated"),
    bigquery.SchemaField("Gnd", "INT64", mode="NULLABLE", description="Flag to indicate ground squat switch active"),
]

from google.cloud import bigquery

table_id = "sbs_pubsub_raw"
table_ref = bigquery.Table(f"{project_id}.{dataset_id}.{table_id}", schema=schema)

client.create_table(table_ref, exists_ok=True)
print(f"Table ready: {project_id}.{dataset_id}.{table_id}")

from google.cloud import bigquery, pubsub_v1

PUBSUB_PROJECT_ID = "qwiklabs-gcp-02-43b1f06a9ba5"
TOPIC_NAME = "flight-transponder"
SUBSCRIPTION_NAME = "flight-transponder-pull-sub"

BQ_PROJECT_ID = "paul-leroy"
BQ_DATASET_ID = "pubsub_feed"
BQ_TABLE_ID = "sbs_pubsub_raw"

topic_path = f"projects/{PUBSUB_PROJECT_ID}/topics/{TOPIC_NAME}"
subscription_path = f"projects/{PUBSUB_PROJECT_ID}/subscriptions/{SUBSCRIPTION_NAME}"

bq_table_fq = f"{BQ_PROJECT_ID}.{BQ_DATASET_ID}.{BQ_TABLE_ID}"
print("Topic:", topic_path)
print("Subscription:", subscription_path)
print("BigQuery table:", bq_table_fq)